### ISSUE TITLE
How to use with vpn to enable multi networks replications

### ISSUE THREAD

**Issue by qymspace** [bergerx/docker-mysql-replication#7]
I need to use multi network replication but unfortunately can't use the usual docker networking due to lack of public ip-addresses. 
I have been enable to enable muti-host container networking using https://github.com/kylemanna/docker-openvpn. Can I use this for replication?
Here is my dockerfile
```from 'bergerx/mysql-replication:5.7'

RUN apt-get update && apt-get install openvpn -y

RUN apt-get install iputils-ping -y

# RUN apt-get install python3.6 -y

RUN apt-get install  curl wget net-tools -y

ADD replication_entrypoint.sh /usr/local/bin/my_replication_entrypoint.sh

RUN chmod +x /usr/local/bin/my_replication_entrypoint.sh

ENTRYPOINT my_replication_entrypoint.sh
```

And in my_replication_entrypoint.sh, I have

```#!/bin/bash
echo "Starting replication"
openvpn --ignore-unknown-option block-outside-dns --config /openvpn/CLIENTNAME.ovpn
# replication-entrypoint.sh mysqld  
```

**Comment by bergerx** [comment]
Hey, I created this repo as a proof of concept project on Aug 2016. It was more than 2 years ago and I have not been looking into this after then. Also since this project has never been used with a real workload ever, and I wouldn't suggest you use it for anything that could be critical in any way.

Regarding the VPN part, I'm not sure I understand what you really mean with "muti-host container networking". If you use a kubernetes cluster with a decent networking implementation you should not need VPN for inter-host communication. You can check https://kubernetes.io/docs/concepts/cluster-administration/networking/#how-to-implement-the-kubernetes-networking-model for some solutions you can use. I don't think I can help you with this question.
